default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CooksCorner_development
  host: localhost
  username: "postgres"
  password: "5432"

test:
  <<: *default
  database: CooksCorner_test
  host: localhost
  username: "postgres"
  password: "5432"

production:
  <<: *default
  database: CooksCorner_production
  username: CooksCorner
  password: <%= ENV["COOKSCORNER_DATABASE_PASSWORD"] %>
